name: Update Profile Info

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - '.github/workflows/update-profile-info.yml'
      - '.github/scripts/generate_assets.py'
      - '.github/scripts/update_readme.py'
  schedule:
    - cron: "0 0 * * 0"  # 毎週日曜 (UTC)

concurrency:
  group: update-profile-info
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    environment: profile-links
    env:
      OWNER: ${{ github.repository_owner }} # ユーザー名
      GH_TOKEN_PRIVATE: ${{ secrets.PROFILE_TOKEN }} # GraphQL 用 PAT
      LAPRAS_ID: ${{ secrets.LAPRAS_ID }} # Secret
      PROFILE_LINKS: ${{ vars.PROFILE_LINKS }} # プロフィールリンク
      WAKA_TIME_SVG_ID: ${{ secrets.WAKA_TIME_SVG_ID }} # WakaTimeSvg
    steps:
      - uses: actions/checkout@v4
      - name: Generate info.json & repos.json
        run: python .github/scripts/generate_assets.py
      - name: Update README
        run: python .github/scripts/update_readme.py

  call-commit:
    needs: update
    if: ${{ needs.update.result == 'success' }} 
    uses: dahutos2/dahutos2/.github/workflows/commit-and-push.yml@main
    with:
      commit_message: "docs: auto update (info)"
